# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Configurador', '0002_auto_20171110_0031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escenario',
            old_name='order',
            new_name='orden',
        ),
    ]
