# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 02:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Configurador', '0003_auto_20171120_0805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('imagen', models.FileField(upload_to='historia/')),
                ('orden', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('suceso', models.CharField(choices=[('A', 'Antes'), ('D', 'Despues')], default='A', max_length=1)),
                ('escenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Configurador.Escenario')),
            ],
        ),
    ]
