# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configurador', '0005_puntaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivel',
            name='bg_image',
            field=models.FileField(upload_to='bgimages/'),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='bg_music',
            field=models.FileField(upload_to='bgmusic/'),
        ),
    ]
